cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'

brew 'ack'
brew 'composer'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'postgresql'
brew 'python'
brew 'python3'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'thefuck'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-completions'

# cask 'docker'
# cask 'firefox'
cask 'font-droid-sans-mono-for-powerline'
# cask 'google-chrome'
# cask 'iterm2'
# cask 'slack'
# cask 'visual-studio-code-insiders'
# cask 'vlc'
